spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: Laoma666
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet-path: /shopping
  port: 2018

