spring:
  type: com.zaxxer.hikari.HikariDataSource
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: Laoma666
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql


