spring:
  type: com.zaxxer.hikari.HikariDataSource
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: Laoma666
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql


#  redis:
#    host: 127.0.0.1
#    port: 6379
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#    timeout: 0

debug: true


